### ISSUE TITLE
Rating没了？

### ISSUE THREAD

**Issue by ELEVENStudio-Main** [hydro-dev/Hydro#203]
版本：v2.35.2
排名页面所有RP均为1500。
运行计算rp脚本，显示：
```
Running script: rp 
Found 3 domains
Found 67 problems in system
Found 2 contests in system
Cannot read property 'hasPriv' of null 
TypeError: Cannot read property 'hasPriv' of null
    at update (/usr/local/share/.config/yarn/global/node_modules/hydrooj/src/script/rating.ts:168:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at runInDomain (/usr/local/share/.config/yarn/global/node_modules/hydrooj/src/script/rating.ts:173:3)
    at Object.run (/usr/local/share/.config/yarn/global/node_modules/hydrooj/src/script/rating.ts:182:7) 
```

**Comment by ELEVENStudio-Main** [comment]
@undefined-moe

**Comment by undefined-moe** [comment]
请确认您是否曾删除过用户

**Comment by ELEVENStudio-Main** [comment]
没有

**Comment by ELEVENStudio-Main** [comment]
所有用户都这样

**Comment by ELEVENStudio-Main** [comment]
数据库操作：
之前设置了一个用户Badge，为了删除把内容设置成了空。

**Comment by ELEVENStudio-Main** [comment]
以及一个建议：把用户Badge设定放进控制面板。

**Comment by ELEVENStudio-Main** [comment]
谢谢

**Comment by ELEVENStudio-Main** [comment]
已经修复，给力
