### ISSUE TITLE
codeforces 域，作业题目：Cannot read property '1' of null

### ISSUE THREAD

**Issue by lxlonlyn** [hydro-dev/Hydro#246]
codeforces 域是按照官方文档上 vjudge 插件整的。

我在 codeforces 域上创建了一个作业，但在作业页面点击题目时，某些题目会出错，显示如下界面：

![image](https://user-images.githubusercontent.com/30793496/140919735-2e02d6b0-c971-4661-ab93-cb9f63b50227.png)

在 pm2 log 中显示这样的错误：
```
3|hydrooj  | 2021-11-09T19:40:21: [E]  server  TypeError: Cannot read property '1' of null
3|hydrooj  | 2021-11-09T19:40:21:         at /usr/local/share/.config/yarn/global/node_modules/hydrooj/src/handler/problem.ts:329:63
3|hydrooj  | 2021-11-09T19:40:21:         at String.replace (<anonymous>)
3|hydrooj  | 2021-11-09T19:40:21:         at ProblemDetailHandler.get (/usr/local/share/.config/yarn/global/node_modules/hydrooj/src/handler/problem.ts:327:22)
3|hydrooj  | 2021-11-09T19:40:21:         at ProblemDetailHandler.validate (/usr/local/share/.config/yarn/global/node_modules/hydrooj/src/service/server.ts:220:39)
3|hydrooj  | 2021-11-09T19:40:21:         at handle (/usr/local/share/.config/yarn/global/node_modules/hydrooj/src/service/server.ts:715:32)
3|hydrooj  | 2021-11-09T19:40:21:         at runMicrotasks (<anonymous>)
3|hydrooj  | 2021-11-09T19:40:21:         at processTicksAndRejections (internal/process/task_queues.js:95:5)
3|hydrooj  | 2021-11-09T19:40:21:         at /usr/local/share/.config/yarn/global/node_modules/koa-static-cache/index.js:53:36
3|hydrooj  | 2021-11-09T19:40:21:         at /usr/local/share/.config/yarn/global/node_modules/koa-static-cache/index.js:53:36
3|hydrooj  | 2021-11-09T19:40:21:         at compressMiddleware (/usr/local/share/.config/yarn/global/node_modules/koa-compress/lib/index.js:52:5)

```

以下信息可能有所帮助：

出现这样错误的题目**全都含有图片**，而且这些题目在题库中浏览时可以正常显示。

我先尝试删除了图片，然后在作业页面的题目就能正常显示了。

但之后我把图片链接原样粘回原处时，题目中的图片无法正常显示（即使不在作业中），显示错误 `Not allowed to load local resource: file://xxx.png/`。

后来我把图片的链接 `file::xxx.png` 改为 `题目编号/file/xxx.png` 后，在所有地方浏览都能正常显示。

想问一下这种错误如何避免？谢谢

**Comment by undefined-moe** [comment]
可否提供对应题目自动导入时的题面文本

**Comment by undefined-moe** [comment]
请测试3.1.27是否可以解决该问题

**Comment by lxlonlyn** [comment]
问题解决了，非常感谢。
