### ISSUE TITLE
[Bug] Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by systemcommunity** [hydro-dev/Hydro#262]
用fps插件导入hustoj的题目时出现问题，错误代码：
#include <string.h>
int main() {
  char answer[42];
  strcpy(answer, "undefined will tell you the answer to life the universe and everything,");
  strcpy(answer, "but first of all, she is very sorry that Hydro meets some issues now.");
  strcpy(answer, "please wait patiently, or contact undefined impatiently about this error.");
  return 0;
}
/*
Invalid or unsupported zip format. No END header found
Error: Invalid or unsupported zip format. No END header found
    at readMainHeader (adm-zip/zipFile.js:101:10)
    at new module.exports (adm-zip/zipFile.js:17:9)
    at new module.exports (adm-zip/adm-zip.js:61:18)
    at FpsProblemImportHandler.post (/fps-importer/handler.ts:115:25)
    at handle (hydrooj/src/service/server.ts:715:24)
    at koa-static-cache/index.js:39:63
    at compressMiddleware (koa-compress/lib/index.js:52:5)
*/

**Comment by undefined-moe** [comment]
请提供对应文件。
