### ISSUE TITLE
v3.13.17题目点击递交按钮，遇到报错提示

### ISSUE THREAD

**Issue by ElementCraft** [hydro-dev/Hydro#372]
- Hydro版本：v3.13.17 Community
 - 部署方式：脚本一键部署
 - 服务器：ubuntu20.04
 
### 问题描述

其他功能暂时测试了都正常，包括在线编程功能也能正常选择提交语言和评测。唯独 “递交” 功能按钮点进去会报错：

```
Failed to call 'afterLoading' of problem_submit,contest_detail_problem_submit,homework_detail_problem_submit
```

然后可选语言列表为空。无法提交评测

可能是获取LANGS列表的时候报错了？

**Comment by ElementCraft** [comment]
web控制台报错堆栈
```
hydro.ts:70 
        
       TypeError: Cannot read properties of undefined (reading 'display')
    at problem_submit.page.js:36:33
    at Generator.next (<anonymous>)
    at 1.accb35b97a.chunk.js:490:533
    at new Promise (<anonymous>)
    at s (1.accb35b97a.chunk.js:490:353)
    at problem_submit.page.js:11:127
    at hydro.ts:65:13
    at Generator.next (<anonymous>)
    at c (1.accb35b97a.chunk.js:529:24632)
```

**Comment by pandadtdyy** [comment]
无法复现 建议自查配置
