### ISSUE TITLE
Hydro 4.7.2 无法备份

### ISSUE THREAD

**Issue by Lixuannan** [hydro-dev/Hydro#502]
当在 Ubuntu 22.04.1 LTS | Kernel 5.15.0-58-generic | Hydro 4.7.2 | Yarn Global v1.22.19 | npm 8.19.2 | nodejs v18.12.1 的环境下，运行 `hydrooj backup` 时的输出如下：
```shell
/bin/sh: 1: yarn: not found
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/ubuntu/.hydro/config.json'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at CAC.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/hydrooj/bin/commands.ts:66:29)
    at CAC.runMatchedCommand (/usr/local/share/.config/yarn/global/node_modules/cac/dist/index.js:614:34)
    at CAC.parse (/usr/local/share/.config/yarn/global/node_modules/cac/dist/index.js:541:12)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/hydrooj/bin/commands.ts:197:9)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.loader (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/utils/lib/register.js:56:19)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/ubuntu/.hydro/config.json'
}
```

而运行 `sudo hydrooj backup` 的输出如下：
```shell
/bin/sh: 1: yarn: not found
Executing:  mongodump mongodb://hydro:dZVFwQf0BdsULHmtGX7ZT83mLLFK9l1x@127.0.0.1:27017/hydro --out=/tmp/v0h7d2jfvcl/dump
/usr/local/share/.config/yarn/global/node_modules/hydrooj/bin/commands.ts:40
    throw res.error;
    ^

Error: spawnSync mongodump ENOENT
    at Object.spawnSync (node:internal/child_process:1119:20)
    at Object.spawnSync (node:child_process:847:24)
    at exec (/usr/local/share/.config/yarn/global/node_modules/hydrooj/bin/commands.ts:21:23)
    at CAC.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/hydrooj/bin/commands.ts:69:9)
    at CAC.runMatchedCommand (/usr/local/share/.config/yarn/global/node_modules/cac/dist/index.js:614:34)
    at CAC.parse (/usr/local/share/.config/yarn/global/node_modules/cac/dist/index.js:541:12)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/hydrooj/bin/commands.ts:197:9)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.loader (/usr/local/share/.config/yarn/global/node_modules/@hydrooj/utils/lib/register.js:56:19)
    at Module.load (node:internal/modules/cjs/loader:1043:32) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync mongodump',
  path: 'mongodump',
  spawnargs: [
    'mongodb://hydro:dZVFwQf0BdsULHmtGX7ZT83mLLFK9l1x@127.0.0.1:27017/hydro',
    '--out=/tmp/v0h7d2jfvcl/dump'
  ]
}
```

**Comment by undefined-moe** [comment]
`nix-env -iA nixpkgs.mongodb-tools`
