### ISSUE TITLE
MongoServerError: User "hydro@hydro" already exists

### ISSUE THREAD

**Issue by brotherYoung** [hydro-dev/Hydro#640]
因服务器宕机，重新运行部署脚本，到安装 mongo 时报错：

**MongoServerError: User "hydro@hydro" already exists
    at Connection.onMessage (/usr/local/share/.config/yarn/global/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/usr/local/share/.config/yarn/global/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/usr/local/share/.config/yarn/global/node_modules/mongodb/lib/cmap/message_stream.js:33:9)**

安装过程终止。

运行环境：docker
容器命令：docker -v "/usr/hydro/data:/data"

我尝试单纯启一个容器，不映射任何文件，部署脚本无任何问题，网站可成功打开。然后将宿主机 data 文件复制到容器 data 内，pm2 resurrect 后，网站 502 无法打开。

请问，我该如何解决这个问题？（很抱歉在这里提问，得到指导后会删除 issue，谢谢。）

**Comment by pandadtdyy** [comment]
hydro的文件不止是data目录 还需要~/.hydro/ 你丢失了配置文件hydro自然认为你没有装过任何东西 开始自动重新安装 而又和你已安装的数据库发生冲突 我们不建议不会用docker的人使用docker部署。

**Comment by brotherYoung** [comment]
@pandadtdyy 谢谢，看文档看到过 ~/.hydro/ 路径，没有重视。请问，没有 ~/.hydro/ 的备份，只是通过宿主机的 data 文件去恢复数据库，能实现吗？

**Comment by brotherYoung** [comment]
解决了，重新恢复数据库可行，麻烦删了吧，谢谢
